-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jul 29, 2022 at 04:13 PM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.0.19

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `laravel_uts`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `name`, `slug`, `created_at`, `updated_at`) VALUES
(1, 'Web Programming', 'web-programming', '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(2, 'Artificial Intelligence', 'artificial-intelligence', '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(3, 'Mobile Programming', 'mobile-programming', '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(4, 'Style', 'Style', '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(5, 'Personal', 'personal', '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(6, 'Kesehatan', 'kesehatan', '2022-05-22 16:17:05', '2022-05-22 16:17:05');

-- --------------------------------------------------------

--
-- Table structure for table `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `uuid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2019_08_19_000000_create_failed_jobs_table', 1),
(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(5, '2022_05_10_070100_create_posts_table', 1),
(6, '2022_05_11_001046_create_categories_table', 1),
(7, '2022_05_19_033137_add_is_admin_to_users_table', 1);

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `personal_access_tokens`
--

CREATE TABLE `personal_access_tokens` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `tokenable_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tokenable_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `abilities` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_used_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `category_id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `publish_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `category_id`, `user_id`, `title`, `slug`, `image`, `excerpt`, `body`, `publish_at`, `created_at`, `updated_at`) VALUES
(1, 2, 5, 'Qui facere doloribus.', 'minus-enim-fuga-aliquam-velit-esse-sint-quo-deserunt', NULL, 'Qui autem debitis debitis ex et error dolorem. Architecto distinctio rem doloribus optio occaecati odit reiciendis.', '<p>Non rerum est nihil sed ut et sequi minima. Aspernatur suscipit quas quia at molestiae.</p><p>Earum omnis facere quia possimus. Porro accusamus hic dicta ut dicta ut qui. Hic quam impedit corrupti excepturi. Ratione repellat est pariatur quibusdam quia qui.</p><p>Nam harum eius quia ut mollitia dolores animi. Aperiam et doloribus tenetur ipsam cupiditate. Ipsa necessitatibus nemo aliquam cumque deserunt molestiae eaque. Quos veniam qui qui libero mollitia.</p><p>Velit velit in veniam odio. Qui libero eligendi ratione architecto. Ratione et et saepe qui ea. Enim nisi illo cupiditate accusantium. Sed doloribus sit nulla.</p><p>Quia provident quos eius distinctio qui occaecati. Earum beatae iure ab alias veritatis dignissimos et. Fugit dolor voluptate doloremque veritatis.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(2, 2, 5, 'Voluptates ab velit.', 'consequatur-molestiae-impedit-doloribus-et-reprehenderit', NULL, 'Ratione et quo mollitia laborum ipsa consequatur vero. Cum architecto nam ut.', '<p>Ea magnam qui dignissimos est explicabo soluta sequi. Reiciendis ut harum dolor ut ut. Dolorem eveniet culpa expedita et quia. Eum consequatur dolore qui et deleniti.</p><p>Reprehenderit atque qui recusandae aut minus voluptas voluptates. Qui sapiente molestias qui laudantium et provident voluptas. Rerum consequatur totam ipsum eaque animi et.</p><p>Similique ut qui iste perferendis. Quia nesciunt aliquam doloribus tempore repellat quibusdam. Et error id illum quam consequatur recusandae velit accusantium.</p><p>Quaerat iusto odit ipsa velit magnam. Ut vitae modi aspernatur modi exercitationem eaque. Adipisci sit et et non animi et ut. Velit unde nam atque accusantium quasi ab alias.</p><p>Est ducimus est id omnis. Optio ducimus atque est sequi ipsam. Quod ea voluptatum aut id earum amet.</p><p>Repellendus fuga unde voluptate id aliquam porro aperiam cum. Quo repudiandae quia id vel enim fuga tempora. Non deserunt quisquam et. Et ipsa qui consequatur et.</p><p>Laboriosam architecto atque expedita provident quidem ex. Perferendis ut quam dolor aut aut qui. Eum qui quos odio id. Aut ab provident cumque.</p><p>Aspernatur eos reprehenderit rerum ratione ipsum ullam ut. Nesciunt facilis laborum voluptate iure. Quo sit deserunt sit.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(3, 2, 4, 'Tenetur fugit exercitationem quia.', 'aliquam-earum-dolore-modi-delectus-placeat-ratione-quos', NULL, 'Eius aspernatur mollitia omnis quo ipsam. Aut est facilis officiis ullam molestias.', '<p>Perferendis rerum omnis enim reprehenderit consectetur quibusdam iste. Placeat animi facere similique odit.</p><p>Enim impedit iusto provident provident nihil aliquid. Minus porro voluptatum est sint omnis. Qui similique molestiae iure ut et.</p><p>Magnam blanditiis esse qui commodi iure quod. Ab aut optio ut.</p><p>Nemo nisi quis tempore. Similique est pariatur itaque repellendus quia enim qui aut. Ratione iste quos numquam fuga vel. Nihil quasi ipsum ratione consequuntur repellat quo ratione.</p><p>Deserunt illo voluptas repudiandae ut asperiores ut voluptas ex. In cum corporis cumque recusandae eum autem.</p><p>Quae autem nihil harum ea quod. Tenetur sunt voluptatem dolore ut similique nihil dicta.</p><p>Non fugit ea assumenda veritatis. Iste commodi voluptates exercitationem. Quia quod sed officiis et.</p><p>Vero qui ullam eveniet aut repudiandae mollitia. Esse tenetur ipsam sit sed aut quod alias. Eum quidem sed itaque fuga autem eveniet quas. Est et ad ut et similique vel.</p><p>Et cum rerum voluptatem ut. Totam cumque sit aut dolorem sed et. Voluptatem enim maxime animi quae et aut.</p><p>Fugit qui corporis veniam commodi reprehenderit nesciunt porro ad. Consequatur nisi debitis quod consequatur sapiente saepe sapiente. Quia enim et aspernatur quis et sequi. Soluta id voluptatum non dolor omnis incidunt deserunt.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(4, 3, 1, 'Qui rem.', 'est-est-nihil-at-et-rerum-fuga', NULL, 'Suscipit explicabo modi ut error.', '<p>Rerum ad odio nostrum fugit quidem dolores repellat. Quo veritatis maxime eum ratione nostrum sit qui voluptatem. Iusto exercitationem expedita sit fuga eius quam non.</p><p>Ut reiciendis debitis numquam aut quod deleniti autem. Eum voluptas voluptate illum ipsam inventore. Autem est incidunt sint autem. Quasi ut mollitia modi aspernatur animi aut et.</p><p>Perferendis modi temporibus dolorem sint itaque. Dolor et aut explicabo laborum qui ratione. Ipsam consequuntur ipsam illo et. Qui quibusdam et inventore quis.</p><p>Qui repudiandae fuga libero cupiditate corrupti consequatur. Magni voluptas illo voluptatum et excepturi ex. Nihil asperiores aut qui sed repudiandae et ipsam et. Nihil voluptatibus voluptatem voluptas voluptatem sit.</p><p>Expedita voluptatibus reiciendis molestias dolorem ut aliquam fugit. Id aliquid aliquid eos eligendi enim at voluptatem laboriosam. Maxime unde natus eum nostrum.</p><p>Molestiae sit accusamus nihil aspernatur beatae. Et unde perferendis minus et dolores officia. Qui autem blanditiis illo rerum esse ab est sequi.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(5, 4, 3, 'A est quis eius sapiente autem.', 'eveniet-sed-dicta-et-nam-non', NULL, 'Sit qui qui quis ut.', '<p>Voluptatum dolores dolorum quis sint. Animi quidem sint quas et similique. Est ducimus vero occaecati quis officia sed. Deleniti quia commodi magni est fugit voluptatem quam.</p><p>Et et possimus non rerum possimus. Fugit a explicabo quibusdam deleniti voluptatem eos. Ipsam tempore est rem.</p><p>Veritatis ipsa neque labore beatae ea. Qui dolore amet odit deleniti quo eaque occaecati. Voluptatem mollitia expedita in vel sed rem maiores.</p><p>Et quod iste accusamus et. Voluptatem porro et dolor illo accusamus et consequatur. Cupiditate dolores earum fugit et magnam ipsam. Amet quo dolore repellat perferendis.</p><p>Similique id sed sed voluptates ad quidem. Ut modi qui corrupti nihil dolor. Quas aperiam quae ea eaque mollitia quasi tenetur.</p><p>Blanditiis possimus nulla libero distinctio omnis rerum ipsam. Ducimus quisquam voluptatem dolorem maiores. Eveniet odio provident cupiditate itaque voluptatem.</p><p>Quis ipsum cupiditate rerum velit aut voluptatem ut. Assumenda ea distinctio maxime libero aut. Voluptates officia optio sunt id sunt. Iusto impedit quod velit est inventore tempore.</p><p>Alias rerum nihil nam alias quas in. Qui laboriosam asperiores mollitia aspernatur possimus. Voluptatem dignissimos qui tempora non accusamus.</p><p>Perferendis est voluptatem quibusdam vel beatae. Nihil beatae ipsum aut consequuntur quis sequi nesciunt. Est non et neque asperiores vitae illo. At error rerum commodi ut.</p><p>Tenetur perspiciatis sequi odio alias quasi fugiat. Quis enim eveniet quo omnis in impedit. Itaque porro qui eligendi aut dolores temporibus non.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(6, 5, 3, 'Eius molestiae temporibus ex dolor.', 'qui-ab-nobis-omnis-atque-reiciendis', NULL, 'Natus doloribus vitae et dolor et.', '<p>Consequatur quis occaecati voluptate est. Pariatur sit dolorem assumenda quisquam animi omnis. Maxime reprehenderit temporibus quo ea quidem. Aliquid debitis enim qui.</p><p>Voluptatibus excepturi consequatur reiciendis esse molestiae dolorem. Qui aut quam aut corporis sit. Alias magnam impedit cumque in. Nemo recusandae rerum eos voluptatem qui laboriosam et.</p><p>Vitae blanditiis quae accusantium quas possimus. Quod minima sed esse corporis. Corporis cupiditate facere accusantium distinctio aut minus hic. Voluptates esse qui suscipit et.</p><p>Molestiae dignissimos quos velit molestiae. Sit accusantium et id harum voluptatem. Corrupti quam harum et molestias. Architecto hic excepturi incidunt nihil tenetur deserunt. Molestiae libero eius molestias totam voluptatem eligendi aliquam totam.</p><p>Quia ex consequatur ut ipsum commodi. Quisquam ut neque reiciendis et accusamus est. Magni dolorum enim aut sunt dolore consectetur quia. Mollitia et fuga dolores et modi.</p><p>Quia nam ut suscipit velit rerum totam. Quos sunt exercitationem atque rem dolore autem. Est veniam enim quia ut voluptatem dolore maiores facilis. Soluta est consectetur est incidunt rerum veritatis id. Dolor blanditiis natus eius at ipsa est in dolore.</p><p>Autem modi atque consequatur qui. Dolore distinctio facilis maiores beatae quia eum.</p><p>Incidunt et expedita saepe aliquid molestias eos ut. Ut sed sed quae architecto quidem. Qui et perspiciatis cumque dignissimos illo recusandae. Deserunt minus delectus nobis.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(7, 2, 2, 'Rerum quia.', 'dolore-laudantium-ut-ea-aut', NULL, 'Qui et expedita eligendi dolor nostrum ratione ratione. Beatae deserunt vero corporis repudiandae sed. Velit qui voluptatibus consequuntur eius iure ut qui.', '<p>Non qui expedita omnis optio nulla et. Rerum non qui cum ipsa qui velit. Consequatur rem impedit vel quia quo laboriosam voluptatem. Praesentium adipisci sunt ut quasi.</p><p>Amet et vero error veniam. Nesciunt delectus reiciendis animi earum. Labore eligendi quo praesentium id. Qui vel odio enim est. Dolores animi libero mollitia consequatur sapiente repellat beatae.</p><p>Consequatur est dignissimos similique quia hic. Natus placeat aut adipisci et sit. Placeat est maiores nemo impedit optio eius possimus.</p><p>Eaque non architecto rem omnis ipsum quo necessitatibus. Quidem quod eveniet exercitationem. Omnis praesentium distinctio architecto similique et. Nostrum suscipit nostrum aperiam veniam.</p><p>Doloribus dicta unde distinctio sit officiis dolores aut. Atque cumque autem qui fuga iure et. Doloribus et sed libero ut delectus et.</p><p>Cumque illo facere et officiis aut pariatur. Ex qui quos dolorum excepturi. Perferendis tenetur illum blanditiis commodi. Earum earum porro id maiores.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(8, 4, 5, 'Excepturi voluptas placeat et.', 'omnis-sequi-hic-labore-inventore-distinctio-ab-est-aut', NULL, 'Voluptas vero nam tempore minima unde laudantium enim. Ut nobis debitis labore quos numquam quis ratione.', '<p>Et natus deleniti deleniti saepe et nostrum consequuntur. Aut dolore ut ipsum fugit aut numquam. Corrupti delectus ipsam et quae voluptatem quia delectus. Maiores corrupti nisi id.</p><p>Itaque ut sunt asperiores non adipisci voluptates dolor. Excepturi voluptatem est aspernatur delectus iure at animi. Consequatur odio et debitis dolores.</p><p>Sint necessitatibus recusandae reprehenderit voluptatem nulla blanditiis. Nihil quo modi sit velit nisi sunt. Impedit ut consectetur error occaecati nihil dolorum. Doloremque non quo occaecati quod cupiditate et.</p><p>Atque eligendi vel quis alias est est. Minima recusandae enim sint dolores assumenda rerum fugit architecto. Molestiae accusamus commodi accusantium eligendi.</p><p>Vitae et fugit aspernatur vel quod sed placeat. Fugiat pariatur esse optio nihil praesentium et qui. Expedita sed numquam non ut officia maiores nam. Voluptatem doloribus pariatur qui aut nesciunt voluptates numquam.</p><p>Dolore est praesentium assumenda odit expedita. Optio voluptas similique qui expedita adipisci enim. Sit dolorem id architecto ad.</p><p>Consequatur fugiat consequatur ut neque aut est. Recusandae quia ut aspernatur ut quis ab. Veniam atque a facilis quisquam facilis animi eius. Sunt non illo consectetur tempora.</p><p>Vitae qui necessitatibus cum aperiam reiciendis. Rerum ea nihil in aspernatur accusamus repudiandae laudantium. Tempore distinctio nostrum velit aperiam earum. Occaecati omnis quibusdam neque architecto quas adipisci perferendis. Vel quia quibusdam iure ipsam et beatae minima.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(9, 6, 3, 'Et facilis dicta.', 'aut-earum-distinctio-in-mollitia', NULL, 'Molestiae alias qui consequatur rerum reprehenderit. Dolorem omnis alias et beatae dolor ea ratione tenetur.', '<p>Ut hic ut eveniet accusamus eligendi. Eius et quam quod nulla. Et harum nam exercitationem eum amet nemo nam provident. Consequatur commodi tempora numquam.</p><p>Recusandae aut sit impedit et voluptas laboriosam dolore ducimus. Molestiae voluptatem magni iure magni. Saepe aliquam omnis et commodi adipisci ut.</p><p>Illo delectus qui ut. Illo praesentium perspiciatis et quia aperiam. Ut minima temporibus voluptatem magni. Eum animi incidunt aspernatur eius. Sit sequi excepturi enim harum.</p><p>Nemo non iusto et voluptates iure est. Atque quasi voluptate at et. Ut fugiat rerum ex quos temporibus officia laudantium. Doloremque omnis ut beatae accusamus voluptates est.</p><p>Incidunt quae tenetur quia delectus autem. Vel laboriosam voluptatem et quidem. Laboriosam sed ducimus nulla est possimus non ab. Excepturi nostrum repellendus sunt possimus. Aut ut facere quisquam hic.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(10, 3, 4, 'Rerum molestiae sit est.', 'dolorem-possimus-amet-quo-est-non-quas-odit', NULL, 'Excepturi temporibus velit fugiat ut rerum. Architecto sit ab maiores et officiis enim ea.', '<p>Consequatur iure repellendus consectetur nobis ipsam eos ipsa. Consectetur aperiam est et quo. Est blanditiis inventore modi neque.</p><p>Placeat saepe ipsa quo eaque sit provident dicta. Reiciendis magni ratione eos illo quo et voluptas. Quo soluta est asperiores sint.</p><p>Quasi voluptas perspiciatis consequatur eveniet sunt placeat sapiente vero. Dolorum iusto ullam ipsum aut voluptas incidunt. Quia possimus sed in ducimus. Exercitationem consequatur aut inventore provident. Inventore pariatur rerum modi est.</p><p>Perspiciatis non asperiores sit rem excepturi veniam. Qui et quod quibusdam dolores est ea. Maiores non consequatur qui soluta non sed.</p><p>Illum est tenetur amet omnis vero. Omnis aliquid et et ut ut quis. Dicta sint mollitia id nulla vel ea voluptas architecto. Non soluta qui et impedit laboriosam quia saepe pariatur.</p><p>Voluptates assumenda beatae veritatis ut culpa. Aut praesentium aut quibusdam. Quod ipsam nobis unde et voluptatem nihil. Praesentium eligendi qui dignissimos accusantium. Amet officia et quis illo numquam voluptatum.</p><p>Repudiandae incidunt et quia non eligendi. Ut quidem nihil dolores consequatur veniam nemo eum. Eum ducimus dolor ab repellat dolorem distinctio.</p><p>Dolor quia dolore est illo voluptatum. Tenetur rerum deserunt autem. Vel aut est repellat explicabo. Culpa aut nihil quidem.</p><p>Sit et ut aut. Nihil numquam quaerat modi cum ullam asperiores. Dignissimos aliquam tempora blanditiis vero. Commodi maiores facilis id sed quaerat consectetur. Qui corporis aperiam quia amet.</p><p>Aliquam earum dolorem consequatur asperiores tenetur suscipit. Magnam voluptatem eum unde consequatur nulla mollitia atque.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(11, 1, 5, 'Aspernatur totam quos aut accusamus ea.', 'et-aliquam-alias-voluptatibus', NULL, 'Est explicabo dolore voluptates aut totam rerum. Repellendus corrupti tempora aliquid nesciunt delectus placeat ut mollitia.', '<p>Rerum illo consequatur blanditiis commodi voluptatem vel. Et architecto quas aut sit corrupti. Id vel perspiciatis omnis architecto.</p><p>Doloremque tenetur eum sunt beatae autem ut nostrum ab. Ea ut illo necessitatibus ut. Iste eius autem quia qui. Quibusdam eos voluptatem libero ullam. Architecto eum nostrum unde accusantium beatae libero sed velit.</p><p>Ut consectetur quibusdam et. Saepe nisi sed et ea non laudantium rerum. Sint sunt officiis doloribus sed eos. Facere quis voluptatibus vel sit.</p><p>Molestiae ad commodi vel unde laudantium eius porro. Repellendus rerum iusto aliquid expedita quia sit quod voluptatibus.</p><p>Eaque quia et quidem placeat. In dolores vel nesciunt omnis earum ut. Molestias eius placeat suscipit natus cupiditate vel. Cupiditate voluptatem et omnis cumque.</p><p>Veniam temporibus iusto et vero quia vel debitis. Laudantium excepturi autem molestiae nostrum optio. Minima accusantium sunt quo illo. Tempore ipsam illo in quos consequuntur. Vitae cumque natus ratione quia reprehenderit.</p><p>Animi praesentium aperiam aut cumque. Autem autem omnis voluptas nihil corrupti esse. Est aut et quidem placeat voluptatem autem sint. Repellendus et ea et sint quo esse. Excepturi rem minima id dignissimos animi sunt tenetur.</p><p>Est amet aut et enim saepe et aut. Et minima veniam at. Quidem iusto consequatur a sed.</p><p>Magni quia pariatur exercitationem aperiam et quidem. Magnam quod repellat ut est animi nihil qui. Rem veniam autem et molestiae ratione ea similique reprehenderit.</p><p>Velit reiciendis ea quod blanditiis. Qui sint reprehenderit reprehenderit velit quia aliquid. Inventore dolor magnam et qui aspernatur adipisci et. Distinctio quibusdam fugit quia maiores esse aut aut dolore.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(12, 2, 4, 'Ut maiores minima excepturi deleniti consequatur.', 'illo-atque-enim-incidunt-praesentium-qui', NULL, 'Eum repellendus necessitatibus beatae mollitia. Aut accusantium fugit pariatur omnis laboriosam dolorem similique vel.', '<p>Sit neque quibusdam omnis tempore voluptatibus ullam repellendus dolores. Consequatur praesentium provident ut quis ipsam. Harum asperiores molestiae autem deserunt.</p><p>Sit magnam qui hic non officiis tenetur ut. Qui et pariatur quia odio sit qui iusto. Exercitationem quidem nesciunt ut explicabo.</p><p>Perferendis praesentium et modi. Aut eligendi assumenda et est exercitationem maiores cumque. Sit dolorem soluta velit perferendis aut.</p><p>Illo velit fuga ipsam. Qui error aut cum quis dolorum nisi itaque. Porro dolor dolorem doloremque doloremque possimus in qui laudantium.</p><p>Maxime neque placeat consequatur commodi. Vero est molestias est id veniam magni. Suscipit vero perferendis sed cupiditate reprehenderit.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(13, 1, 3, 'Voluptatem rem voluptas non.', 'doloremque-ducimus-rem-molestias-ab-ut-est-ipsam', NULL, 'Provident tempore rerum ad voluptas explicabo. Dolorum quia esse earum omnis.', '<p>Corporis non quidem in nihil. Qui minima sed enim illo aut sit. Quisquam eius vel dolorem vero iste. Debitis quaerat nulla et non aliquam consequatur fuga.</p><p>Ipsam suscipit aut possimus. Corrupti sunt iure iste numquam. Dolores aliquam et libero et velit quaerat veritatis.</p><p>Architecto doloribus eum qui quod qui quia. Ipsam velit commodi sed a officia. Molestias explicabo a enim placeat dolorem et tempora vel. Iste ut inventore veniam repellat totam libero id. Laboriosam consequatur ut sunt.</p><p>Repellat voluptate sit consequatur et. Voluptatem culpa et molestias esse ex sint rem veritatis. Dolor aliquid dignissimos dolore sed quod sed est. Enim ducimus debitis voluptatem neque tenetur aut voluptates.</p><p>Sed consequuntur quisquam sit at. Nobis consequatur mollitia quaerat quas ut perferendis quae quam. Nostrum sint aut molestiae harum corporis illo dolorem sit.</p><p>Eaque consequatur fugit amet sed reprehenderit veritatis porro. Consequatur necessitatibus ut est dicta impedit corrupti. Omnis quia velit illo eos. Ex sit ipsum iusto soluta expedita.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(14, 5, 5, 'Velit non quo rerum.', 'nostrum-iure-reprehenderit-rerum-reiciendis-corrupti-rerum-facilis', NULL, 'Cumque nesciunt officiis maiores atque velit quo. Quia est assumenda odit exercitationem maxime qui.', '<p>Velit dignissimos ex accusantium dolor voluptate consequatur. Corporis eum cupiditate ut aut vitae omnis quam est. Et quasi aut accusamus excepturi excepturi.</p><p>Cum laboriosam numquam quo optio et voluptas exercitationem. Sit ad amet adipisci quasi qui cupiditate. Laboriosam porro sit dolorum quaerat perferendis.</p><p>Dolores quo sed quasi quis iste vel. Ut sunt vero aut eligendi. Consequatur asperiores quia eum dolorem nostrum. Quo ut culpa et.</p><p>Nisi culpa expedita quia. Culpa eos magnam sunt excepturi. Eos nulla omnis molestias ipsum corporis rerum sint. Et consequuntur itaque error nisi laborum doloribus. Est tempora dicta ipsum officiis.</p><p>Officia ullam consectetur quasi eius non. Neque aut qui quia nihil quis ea quia voluptatibus. Cum nobis ullam nulla voluptas commodi. Numquam numquam voluptatibus doloribus similique aut ut nobis aut.</p><p>Eius quia occaecati dolorum iure pariatur dolor nobis aut. Omnis laboriosam atque impedit eligendi. Et sit quisquam totam sit aperiam vitae. Sunt est consequatur nisi eum et mollitia maxime.</p><p>Dolorem sit nisi architecto corrupti odit sint voluptatem blanditiis. Nobis necessitatibus quia qui quibusdam maxime corporis. Officia ut hic repellat nam. Eum quia qui quidem illo vel iusto.</p><p>Impedit exercitationem voluptas eos quis neque nostrum. Quae accusamus blanditiis culpa occaecati est nostrum.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(15, 6, 1, 'Molestiae libero repudiandae quia.', 'voluptas-amet-et-ut-optio-molestias-odit-ullam', NULL, 'Qui necessitatibus blanditiis id et aliquam corporis voluptatum. Consequatur debitis facilis aliquam tempore non sunt et perspiciatis.', '<p>Nisi optio aspernatur modi commodi. Sed similique corporis sapiente ut. Sed eos blanditiis natus error perspiciatis tenetur eos. Harum odio et et omnis dicta omnis.</p><p>Ut omnis at consequuntur neque. Quia rerum suscipit repudiandae. Quos a cum eum dolores rerum. Pariatur aut ratione ex vel laborum aut quo. Maiores enim quidem id laudantium voluptatem consequuntur.</p><p>Cumque est nesciunt magni. Numquam sit eius repellendus porro odit ratione. Ut sed nisi omnis corporis cupiditate atque rerum vel. Facere aliquid ut nihil in. Fuga et consequatur ducimus sed.</p><p>Sed suscipit quisquam accusantium aut velit voluptatem. Odit sunt qui praesentium saepe dignissimos quibusdam. Esse itaque molestiae nobis voluptas quae incidunt fuga. Tenetur eligendi nesciunt qui quibusdam quis consequatur voluptas.</p><p>Porro numquam eum a non esse consequuntur ducimus saepe. Voluptatem quas explicabo aut reprehenderit dolore.</p><p>Rem velit soluta saepe culpa dolores quia quibusdam. Quis voluptatem dolorem similique eveniet recusandae et. Adipisci cum sapiente enim.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(16, 2, 3, 'Est facere amet voluptatem id placeat.', 'rem-inventore-quo-dolorem-numquam-at-voluptas-a-consequatur-reprehenderit', NULL, 'Quis quae quia eligendi.', '<p>Temporibus eaque quis consectetur itaque similique porro saepe. Qui nulla fugit quia molestiae consequatur et sequi. Minima dolore cumque blanditiis laborum.</p><p>Ut non autem at quam eos error. Qui voluptatem nihil facere qui consectetur.</p><p>Qui velit quae beatae occaecati beatae. Commodi odio quia harum et molestiae libero. Accusantium perferendis assumenda non ullam magni ipsum omnis. Voluptatem aut qui deserunt nesciunt fugit.</p><p>Aliquam autem id perspiciatis natus et. Error provident suscipit voluptatem ullam. Esse aliquam reprehenderit quia voluptatem a. Iste totam sit eligendi possimus.</p><p>Corporis libero doloremque quidem non soluta aut. At dolor qui aut animi facilis distinctio natus sit. Et dolor quos architecto a nesciunt.</p><p>Animi qui dolores sunt nesciunt quia nobis. Animi sequi velit sit labore. Fuga a est sunt soluta consequatur dolores.</p><p>Modi autem neque eveniet voluptate vel. Asperiores recusandae est qui doloremque corrupti voluptas. Nihil animi voluptas qui et id. Impedit ut at magnam.</p><p>Eos rerum aspernatur quos exercitationem quis est eligendi sint. Aut illum a a necessitatibus doloribus doloremque. Facere voluptates architecto et corporis sunt.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(17, 3, 3, 'Nemo aliquid placeat est.', 'ea-illo-dignissimos-eum-facere-omnis-est', NULL, 'Aliquam sunt numquam cupiditate sed reprehenderit facere. Aliquam iure sit sed numquam.', '<p>Qui ea ea quibusdam atque fuga facere corrupti. Omnis consequuntur beatae magni eaque. Sint labore facere ut aut debitis dolore reprehenderit dolorem. Provident beatae voluptatem reiciendis velit et.</p><p>Consequuntur ab a nulla corrupti. Molestiae qui voluptas eos fugiat dolorem. Cum error et velit ut tempora voluptatum aut itaque. Atque beatae quidem labore et eos et minus.</p><p>Provident modi dolores voluptatem autem vero sit et. Tempore veniam maiores magnam blanditiis omnis voluptatem. Ullam omnis consequatur iste debitis tempora quasi sit. Voluptas quae quam rerum quae itaque facere quaerat.</p><p>Quis voluptas aliquid labore similique nemo. Est rerum officia ea.</p><p>Nam quisquam excepturi error et reiciendis. Laborum suscipit molestiae ab et veniam quo sequi.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(18, 6, 3, 'Autem magni.', 'numquam-quae-aperiam-voluptatibus', NULL, 'Soluta reiciendis ratione velit impedit enim accusamus. Et laborum laborum atque commodi quos.', '<p>Animi quod quisquam quo fugiat. Totam nihil nihil natus a nihil qui.</p><p>Doloribus excepturi maxime beatae est architecto explicabo. Dignissimos culpa beatae id et est. Sed incidunt repudiandae officiis. Dolor pariatur delectus aspernatur nisi.</p><p>Laboriosam placeat quia cupiditate nihil eveniet. Qui inventore minima labore eum dolores reiciendis. In consequatur odio accusantium cupiditate quod velit.</p><p>Qui quo ipsum natus eum labore illum neque et. Dolorem eos corporis ea aut dolore possimus.</p><p>Asperiores veritatis facilis officiis esse sed eveniet. Quos inventore voluptatem molestiae harum. Sed non dignissimos molestiae voluptas.</p><p>Quia culpa error qui facilis sapiente consequatur. Sapiente veniam odit omnis ipsa veritatis in. Sint inventore amet iure et et cumque. Ratione facere minima id rerum sunt et dolor.</p><p>Omnis accusamus magnam omnis cupiditate dicta maxime dolorem. Quidem dicta dignissimos unde reprehenderit minus voluptatibus. Quod et officia voluptatem labore numquam voluptate impedit eum. Possimus et quas sed ut beatae necessitatibus iusto sequi.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(19, 1, 3, 'Ducimus vel soluta temporibus.', 'vitae-autem-quod-sed-nihil-ab-voluptatibus-voluptatem', NULL, 'Optio qui illum nihil architecto temporibus et. Et hic ipsum iusto laboriosam.', '<p>Aut laboriosam quia adipisci. Impedit velit ab dignissimos nihil. Illo sint corporis harum vero. At expedita optio vitae natus odit.</p><p>Voluptas et quibusdam voluptatem eveniet hic natus culpa. Fugiat quia rerum vitae iste. Et est sapiente deserunt.</p><p>Quidem ut mollitia quo. Error dignissimos repellendus iusto tenetur et quia. Culpa officia et quo distinctio ea ut. Corrupti autem autem soluta.</p><p>Beatae quae dignissimos consequuntur nihil non quas. Rerum architecto quisquam omnis voluptate in et. Sed consequatur et eum eveniet at enim harum nobis. Esse facilis possimus similique atque.</p><p>Cum numquam impedit reprehenderit ea ex omnis iste. Quia aut mollitia exercitationem ut nihil.</p><p>Harum et sed quibusdam totam autem. Quas similique id at accusantium accusantium dolores ut. Aliquam et omnis veritatis.</p><p>Voluptas quo dolorum incidunt. At eveniet corporis iure occaecati et quibusdam aut. Non eum quibusdam quaerat sint fuga.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(20, 4, 3, 'Eligendi sed animi quis.', 'ut-est-quia-et', NULL, 'Magnam molestiae laborum iste voluptate ut. Ea aut sapiente similique accusantium quidem vel amet ea.', '<p>Voluptates dolorum odio ab ad. Est tempore iste eum laborum quia omnis. Autem quia et ipsa maiores quam eos eum.</p><p>Sint excepturi perferendis quos ullam rerum est eveniet veniam. Aut quod ut cum perspiciatis molestias quasi. Veniam blanditiis harum excepturi ea earum et aut.</p><p>Saepe voluptas quas illo omnis aut eos aperiam. Inventore molestiae atque ab voluptatem est. Sit iure adipisci ea illo.</p><p>Voluptatibus esse quis debitis quam cupiditate doloremque vel. Quos quas aut rerum amet perspiciatis consequatur eos. Et vitae mollitia esse saepe minima illum error. Sint qui ducimus qui.</p><p>Quod quaerat sed quia tempore non ad. Dolores aperiam quo id non consequatur placeat. Consectetur et in aut hic rerum dicta sit ipsum.</p><p>Est quo soluta perferendis sapiente dignissimos. Distinctio itaque saepe veritatis hic. Quo quae maxime similique placeat atque qui et.</p><p>Inventore ut debitis iusto quo omnis. Sed sint necessitatibus ipsa asperiores distinctio. Commodi exercitationem inventore enim alias.</p><p>Dicta quis ad non optio. Eaque molestiae amet qui pariatur autem alias ut id. Dolorem in autem consequatur molestiae. Iure a quia est quaerat dolorum doloremque. Temporibus dolor dolores optio eum.</p><p>Et est eum ratione optio dolorum at. Sed quia voluptas pariatur iusto corporis. Nam dolores voluptas sint facilis ipsa ut. Ea tempora tenetur perferendis sed reiciendis.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(21, 3, 4, 'Harum eum voluptatem omnis expedita qui consectetur consequatur.', 'et-perferendis-doloribus-tenetur-dolores', NULL, 'Dolorem dolor molestiae vel et libero temporibus facilis. Nemo minima ut velit qui. Fuga soluta in ducimus ea consequuntur.', '<p>Nam amet iusto accusamus beatae at nihil. Officia tempore minima earum illo voluptatem magnam deserunt voluptatem. Et autem culpa aut autem aut consequuntur exercitationem.</p><p>Consequatur et aut quia et repellendus corporis delectus error. Ab sit ea nemo laudantium inventore. Consectetur nisi dolore quod fugit. Iure et maiores possimus ut dolorum.</p><p>Veniam qui ut deserunt sunt magni. Consequuntur qui ab reprehenderit fugit quas culpa cum. Magni consectetur officia delectus in est recusandae perferendis aut.</p><p>Minus animi sit et vel. Beatae recusandae alias dolorem excepturi. Et quia cum est laboriosam debitis aut.</p><p>Asperiores quo illum odit et incidunt rerum. Non illum sit excepturi ab.</p><p>Quaerat similique veniam ea impedit. Eos et consequatur fugit repellat totam sint sed.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(22, 5, 5, 'Ducimus totam.', 'asperiores-aut-consequatur-et-eveniet-dignissimos-voluptas', NULL, 'Voluptas eos ratione consequatur distinctio earum fugit.', '<p>Eveniet id aut exercitationem. Eaque qui esse vero. Neque non ab praesentium vitae ab omnis voluptate. Nostrum aut fuga qui fuga veritatis.</p><p>Nihil libero deserunt omnis dolorem autem. Temporibus porro laboriosam omnis asperiores nisi quia dolor. Non et minima officia quas voluptates itaque. Fugiat fuga ea quo debitis.</p><p>Velit aspernatur facilis in. Vero et exercitationem quas et labore quam magni. Quia maiores recusandae placeat quaerat. Natus iusto eligendi dolore magni voluptate.</p><p>Aperiam tempore veritatis ut eveniet est. Expedita sint quo et neque et fuga corporis inventore. Temporibus eius libero assumenda. Doloribus libero non velit error sed autem saepe.</p><p>Quidem vero autem tempora est et. Libero ea soluta itaque optio aut et. Suscipit est omnis qui eveniet dignissimos est.</p><p>Ut nisi nihil voluptatum nobis delectus quibusdam quo atque. Sit consequatur eius voluptas et ducimus. Sed doloribus ipsa inventore assumenda.</p><p>Nam ea ab impedit commodi. Hic quos alias impedit aut nam veritatis unde. Vel inventore minus soluta beatae voluptate. Ipsa exercitationem cumque esse et nisi. Ut amet quo recusandae incidunt.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(23, 2, 5, 'Ullam sint ipsa sint.', 'et-iste-blanditiis-qui-ut-et-dolorem-consequuntur', NULL, 'Et veniam enim aut dolores et eveniet sapiente libero. Non doloribus fuga mollitia aliquid quam odio. Eaque eum placeat sit id ipsum neque autem autem.', '<p>Commodi in dolor inventore alias molestiae qui hic. Sunt quidem sit possimus voluptatibus dicta provident. Consectetur rerum dolore tempora eum blanditiis quisquam. Eum quam corporis expedita magni itaque reiciendis velit.</p><p>Velit et quisquam consectetur eum fuga explicabo. Ipsa ea aut laudantium eius. Ut et tempore nulla et iusto soluta deleniti ut. Amet exercitationem recusandae repellendus optio.</p><p>Et qui facilis minus ducimus dolorem quas quibusdam. Dolorem veniam dignissimos asperiores et est modi dolorum. Necessitatibus inventore et beatae quia corrupti exercitationem minus. Nostrum ut fugiat saepe quibusdam aut nobis delectus commodi. Non necessitatibus exercitationem consequatur et vel in sed cumque.</p><p>Quo deserunt possimus aspernatur magni quos. Iste at vel ea reiciendis nihil. Dolor labore omnis ea aut quia porro repellat. Nemo et quia voluptatem ipsum saepe voluptates.</p><p>Aut commodi qui numquam. Fugiat optio provident ut nisi id architecto libero. Totam hic vel adipisci.</p><p>Sint eos sequi neque enim eius consectetur. Excepturi consectetur rem consequatur voluptas ducimus et. Deserunt ad ut qui et aperiam beatae aliquid in.</p><p>Sapiente vel odit voluptas in. Soluta labore architecto molestiae occaecati est veniam. Sunt aliquid id perferendis sit sed. Vel cum est quo ad rerum iusto enim.</p><p>Est accusantium ratione officiis culpa omnis beatae. Qui vel sequi deserunt rem. Similique voluptatibus omnis eos qui sed accusantium itaque voluptas.</p><p>Eaque et porro reprehenderit et. Ad non reprehenderit non laborum.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(24, 4, 4, 'Quas possimus sit vero.', 'magni-veniam-natus-numquam-exercitationem-voluptas', NULL, 'Mollitia nam assumenda doloremque non quam.', '<p>Minima mollitia id aut quaerat et impedit saepe. Earum magni amet illo vel. Eum ab quis eum doloremque quod et omnis ut.</p><p>Laudantium ut amet nisi nemo voluptas quia. Veritatis consequuntur animi voluptate perspiciatis necessitatibus quo repudiandae reprehenderit. Molestiae hic dolorem accusantium sint ad ut molestiae. Dignissimos omnis a omnis consequuntur eius quasi. Pariatur incidunt ut suscipit similique dolorum autem.</p><p>Et in nulla qui repudiandae. Quo nesciunt fuga dolorum dolore. Error totam et a.</p><p>Magni doloribus tempore est molestias sit. Eum dolorum delectus eveniet assumenda. Delectus distinctio qui neque culpa. Ut officia cum officia debitis.</p><p>Id nemo sint maiores consequatur. Nemo officia ut et unde necessitatibus unde autem. Enim qui beatae repellendus alias ut. Sed quis commodi et voluptas autem.</p><p>Consequatur dicta est soluta quam. Molestiae cum omnis sed itaque earum quo asperiores. Praesentium quis expedita consequatur maiores sunt soluta tempore. Natus omnis quis sed quia aut.</p><p>Necessitatibus excepturi velit optio sint ducimus cumque harum. Et qui possimus voluptatum soluta. Laboriosam et quidem accusantium quo hic.</p><p>Architecto qui tempore et. Amet explicabo error reprehenderit placeat veniam quas. Ipsum ea odio nihil modi corrupti inventore.</p><p>Omnis nesciunt sed iusto sit consequatur. Veritatis id voluptas commodi. Reprehenderit qui officia consequatur.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(25, 1, 5, 'Doloremque asperiores autem blanditiis.', 'distinctio-harum-ratione-doloribus-nihil-molestiae-quia-quod', NULL, 'Quo ipsam qui enim voluptatibus dicta aut. Possimus ipsa beatae numquam suscipit pariatur cum laboriosam eveniet.', '<p>Nisi iste consequatur cumque vitae. Voluptas sint vel voluptate consequatur rerum cum. Nihil reiciendis et voluptatem autem. Sint magnam eveniet est quibusdam sunt facilis.</p><p>Quos omnis error et et. Officiis suscipit excepturi quia excepturi et ipsa. Quia quas natus sit voluptatem.</p><p>Incidunt quae quo quibusdam quam accusantium id possimus quia. Saepe veniam aspernatur dolor et quibusdam dolorem. Error accusamus debitis hic eos rem quis. Ab quis autem eum quisquam nisi est a.</p><p>Soluta inventore dolorum quis itaque. Laudantium eum suscipit ipsa reiciendis voluptate.</p><p>Omnis sit repudiandae sint. Dolorum voluptate ipsum vel sequi. Optio cumque quisquam nemo optio voluptatem id esse. Cumque iusto enim asperiores et ullam dolore ut architecto.</p><p>Sapiente voluptas iure vel rerum sed dolores suscipit dolores. Qui ratione et quo eligendi sint quibusdam ut quas. Molestiae adipisci iste nostrum ducimus debitis nostrum ducimus nobis.</p><p>Eligendi ut a temporibus ipsa ab. Pariatur itaque reiciendis dolores eos vel odio molestias. Illo impedit et eaque ut repellat quia sed.</p><p>Tenetur ut ut molestiae velit. Odio laboriosam in tempore quis quo quas sunt. In quia eum eos nostrum.</p><p>Vero quas est ut delectus. Est iusto rerum optio consequatur culpa voluptate distinctio. Dolores optio odit vel omnis maxime enim laudantium.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(26, 3, 3, 'Quis sit error.', 'beatae-nam-rerum-culpa-assumenda-neque-molestiae-non', NULL, 'Et cumque rem sapiente sunt voluptates sapiente. Corrupti eligendi et est consequatur. Voluptas fugiat inventore sunt eos nisi.', '<p>Et qui fugit quia libero. Est aut quis non. Unde voluptatem occaecati nemo explicabo. Autem tenetur minima exercitationem quasi.</p><p>Dolor et qui quaerat veniam ut vel dolores. Eum omnis nobis deleniti eligendi accusantium. Atque perferendis saepe atque ab. Nihil ea error ad est.</p><p>Accusamus cupiditate sed eaque dicta. Nostrum voluptatem aut quis illo aliquid. Quam facere qui eum quia. Recusandae blanditiis aperiam facere error. Et quod et optio dolorem neque debitis.</p><p>Dolores est quae modi aliquam fuga. Qui totam assumenda nisi ea. Corrupti quod debitis dicta accusamus.</p><p>Quod error harum earum possimus. Cum animi quibusdam nam est nam. Totam sit temporibus aut velit libero.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(27, 5, 2, 'Sequi sed sint asperiores veniam.', 'nihil-id-non-amet-tempora-id-rerum', NULL, 'Autem numquam perspiciatis qui inventore eveniet natus eius.', '<p>Est ea animi corporis fuga qui voluptatem. Occaecati itaque harum minus minus eos suscipit. Consequatur nihil itaque quis dolorum aspernatur. Culpa architecto rerum ea officiis.</p><p>Nisi et ab velit sed et voluptatem. Hic quaerat consequatur omnis accusamus rem aut quam. Possimus soluta aut quibusdam dolores sequi dolorem. Est et iure cupiditate ut consectetur at dolores.</p><p>Et placeat neque dolore quia vitae expedita quod. Enim consequatur velit deleniti. At aut sed neque ut aut. A placeat omnis quia.</p><p>Praesentium similique vel aut architecto. Nam tenetur et in quod et quia quae. Dignissimos excepturi totam aliquid voluptatum.</p><p>Quae eaque voluptatem commodi. Et iusto aut sit alias. Saepe magni iste aliquid autem nisi delectus quibusdam. Porro itaque molestiae dolor explicabo sint eum.</p><p>Modi qui deleniti alias necessitatibus iste veritatis. Ullam commodi nulla qui qui incidunt. Nihil id reiciendis amet dolorem molestiae fugiat sit.</p><p>Magni porro aut illo debitis ut ex iste labore. Blanditiis ab quia beatae nam perspiciatis ipsam. Temporibus vitae ipsa omnis et impedit quam.</p><p>Qui nulla ducimus velit itaque et inventore. Eius illum et dolorem omnis repellendus. Enim consequatur impedit expedita esse odit cum.</p><p>Ut molestiae corrupti vel voluptatum et architecto. Autem hic eveniet in laborum.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(29, 2, 4, 'Tenetur laborum laudantium.', 'quis-repudiandae-alias-consequuntur-et-dolorem-qui', NULL, 'Tempore voluptatem quisquam asperiores nihil nisi velit.', '<p>Consequatur eligendi labore ut est sit. Hic cum sit consequatur iure. Optio quia ea magnam expedita unde sunt.</p><p>Explicabo totam iure necessitatibus odio dicta. Sed accusamus accusantium ex ut deleniti.</p><p>Incidunt rem quia est. Et corporis sed minima doloremque et aut dolorem explicabo.</p><p>Corrupti voluptate sunt corporis vitae eum dignissimos exercitationem. Sint dolores saepe eum est. Ea adipisci maiores necessitatibus quisquam velit.</p><p>Ut quo ratione atque officia sint exercitationem. Qui nemo ab porro quia quia est. Aliquam totam et mollitia nihil fuga. Dolor in blanditiis voluptatem qui accusamus.</p><p>Dolore dolorem facere dolores quasi. Sit quis facere qui tenetur non vel mollitia itaque. Voluptate ut quisquam esse ut magnam dolorum iste.</p><p>Quia est accusantium quia quo aut aut qui deserunt. Aliquid eius labore rerum soluta aut optio porro sit. Eligendi quia dicta et voluptatem animi illum. Tempore illo tempore sequi unde fugiat molestiae.</p><p>Adipisci fugit est est aliquid nihil tempore. At voluptatem consequatur odit explicabo est quo voluptas. Temporibus modi fugit optio aliquam.</p><p>Fugit quis aperiam qui vel asperiores sunt aperiam. Accusamus aut maxime provident quis officia voluptatibus impedit tempore.</p><p>Pariatur fugit non architecto aliquid id dolore. Animi consectetur et in voluptatem consequuntur dolore. Quis laborum esse ullam dolorem est fugit commodi doloribus.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(30, 3, 4, 'Perspiciatis et aut eos.', 'doloremque-et-unde-magnam-ut-facere-nesciunt-corporis-qui', NULL, 'Non est quia quis nisi. Velit nihil nesciunt laboriosam cupiditate.', '<p>Voluptas accusantium iusto pariatur itaque numquam nihil nesciunt reiciendis. Dolorum recusandae iusto ad numquam. Optio provident quia dolorem consectetur perferendis et hic doloribus. Ipsa consequatur aut porro minima totam molestiae hic.</p><p>Placeat voluptatem tenetur doloremque cupiditate at labore. Et accusamus cumque assumenda aliquam. Eum exercitationem temporibus officia.</p><p>Deleniti ut incidunt quia. Maiores hic illo assumenda et adipisci totam omnis. Voluptas debitis provident non. Dolor doloribus aut aliquid aut.</p><p>Animi ipsam molestias qui. Sit cum quis quia quia placeat ut in aliquam. Ad tempora nesciunt dolores vitae.</p><p>Ut quis consectetur dolorem ut. Quaerat eum doloremque placeat nihil soluta id et. Est rerum recusandae vitae est nemo. Reprehenderit et aut earum sint consequatur sequi officiis porro.</p>', NULL, '2022-05-22 16:17:05', '2022-05-22 16:17:05'),
(31, 6, 4, 'Dampak Kurang Tidur untuk Perkembangan Otak Anak', 'dampak-kurang-tidur-untuk-perkembangan-otak-anak', NULL, 'Dampak Kurang Tidur untuk AnakBeberapa orang mungkin menganggap bahwa cara tepat untuk mengatasi kurang tidur adalah mendapatkan waktu tidur lebih banyak di hari berikutnya. Kenyataannya, kurang tidur...', '<div><strong>Dampak Kurang Tidur untuk Anak</strong><br><br>Beberapa orang mungkin menganggap bahwa cara tepat untuk mengatasi kurang tidur adalah mendapatkan waktu tidur lebih banyak di hari berikutnya. Kenyataannya, kurang tidur tidak selalu dapat diatasi dengan tidur ekstra di malam berikutnya.<br><br>Seiring waktu, menurunnya kualitas setiap malam dapat memberikan dampak pada&nbsp; perilaku, kognitif (mental) dan emosional anak. Nah, berikut gejala yang bisa ditimbulkan dari kurang tidur.<br><br><br>1. Dampak kurang tidur untuk fisik anak:<br><br>Susah bangun pagi.<br>Tertidur setelah dibangunkan.<br>Sering menguap di siang hari.<br>Mengeluh merasa lelah atau ingin tidur siang.<br>Lebih suka berbaring di siang hari.<br>Tertidur atau tampak mengantuk di sekolah atau di rumah.<br>Ingin mengkonsumsi stimulan yang tidak sehat, seperti kafein atau gula, secara teratur.<br><br>2. Dampak kurang tidur untuk kognitif (mental) anak:<br><br>Kurang minat, motivasi dan perhatian untuk mengerjakan tugas sehari-hari.<br>Mudah lupa.<br>Penglihatan kabur.<br>Kesulitan mempelajari informasi baru.<br>Gejala emosional.<br>Peningkatan kemurungan dan lekas marah.<br>Peningkatan impulsif.<br>Mudah stres.<br>Utang tidur yang besar tidak akan cukup dibayar dengan tidur selama beberapa malam berturut-turut. Pada akhirnya, utang tidur ini dapat menyebabkan anak merasa lelah secara mental. Ini juga dapat memperburuk gejala gangguan perilaku, kecemasan, dan suasana hati seperti depresi atau gangguan bipolar.<br><br></div>', NULL, '2022-05-22 16:23:52', '2022-05-22 16:23:52'),
(32, 4, 4, 'Tampil Percaya Diri dengan Fashion Kasual', 'tampil-percaya-diri-dengan-fashion-kasual', NULL, 'Style Kekinian ?Mau tampil lebih colorful dari biasanya, coba pakai sweatpants yuk! Walaupun memiliki fungsi utama sebagai celana olahraga, sweatpants bisa kamu pakai sehari-hari untuk gaya outfit yan...', '<div><strong>Style Kekinian ?</strong><br><br>Mau tampil lebih colorful dari biasanya, coba pakai sweatpants yuk! Walaupun memiliki fungsi utama sebagai celana olahraga, sweatpants bisa kamu pakai sehari-hari untuk gaya outfit yang lebih keren lho. Nggak sulit untuk memadu-padankan sweatpants supaya terlihat kasual, cukup dengan gunakan fashion item yang tepat, kamu sudah berhasil tampil layaknya fashionista. Misalnya memasangkan sweatpants merah dengan hoodie dan coat, atau bergaya kekinian layaknya Billie Eilish dengan t-shirt dan beanie. Selengkapnya scrolling downs sekarang juga!<br><br><br>1. Sweatpants bisa berubah jadi semakin high fashion dengan mix &amp; match yang tepat lho. Mulai dengan memasangkan sweatpants dengan coat super tebal dan sneakers. Keren!</div>', NULL, '2022-05-22 16:24:38', '2022-05-22 16:24:38'),
(33, 5, 3, '5 Tips Untuk Membangun Personal Branding di Sosial Media', '5-tips-untuk-membangun-personal-branding-di-sosial-media', NULL, '5 Tips Untuk Membangun Personal Branding di Sosial Media Di era digital sekarang ini banyak sekali sosial media (sosmed) bermunculan. Sosial media, seperti Facebook, Instagram, Twtter, YouTube, sampai...', '<div><strong>5 Tips Untuk Membangun Personal Branding di Sosial Media </strong><br><br>Di era digital sekarang ini banyak sekali sosial media (sosmed) bermunculan. Sosial media, seperti Facebook, Instagram, Twtter, YouTube, sampai LinkedIn tentu punya peran positif kita, termasuk Anda. Salah satu dampak positif dari penggunaan sosial media adalah untuk membangun sebuah personal branding.&nbsp;<br><br><br>Sebelum membahas tips membangun personal branding, cari tahu dulu apa arti dari personal branding. Menurut Wikipedia, personal branding adalah proses di mana orang-orang dan karier mereka berlaku layaknya sebuah produk. Personal branding seringkali dikaitkan dengan suksesnya karier seseorang. \"Personal Branding adalah cara dan proses kita memasarkan diri kepada orang lain atau komunitas yang menjadi target kita.\"<br><br>Gelombang sosmed makin kuat. Setiap hari tidak lepas dari yang namanya sosmed. Update status, posting foto, video, atau konten menarik lain bukan hanya untuk eksistensi semata, tapi juga membangun personal branding. Kini penilaian orang lain terhadap pribadi seseorang juga didasarkan pada perilaku mereka di sosmed.<br>Tidak peduli apa jenis bidang karier yang Anda tekuni atau sedang dirintis, kehadiran Anda di berbagai sosmed amatlah penting untuk menyebarkan pesan pada orang lain tentang siapa dirimu. Kalau kamu merasa aktivitas berbagi, menyukai atau mengikuti sesuatu di sosmed tidak terlalu penting, maka siap-siap saja untuk duduk dan menikmati ribuan bahkan orang di luar sana yang berhasil mendapatkan perhatian dari orang lain di sekitarnya.</div>', NULL, '2022-05-22 16:26:04', '2022-05-22 16:26:04'),
(34, 1, 3, 'Pengertian dan Pengenalan Pemograman Web', 'pengertian-dan-pengenalan-pemograman-web', NULL, 'Pengertian Web ProgrammingPemrograman web diambil dari 2 suku kata yaitu pemrograman dan web. Pemrograman yang dalam bahasa English adalah programming dan diartikan proses, cara, perbuatan program.Def...', '<div><strong>Pengertian Web Programming</strong><br><br>Pemrograman web diambil dari 2 suku kata yaitu pemrograman dan web. Pemrograman yang dalam bahasa English adalah programming dan diartikan proses, cara, perbuatan program.<br><br>Definisi Web : jaringan komputer yang terdiri dari kumpulan situs internet yang menawarkan teks dan grafik dan suara dan sumber daya animasi melalui protokol transfer hypertext.<br><br>Orang banyak mengenal web dengan istilah WWW (world wide web), World Wide Web adalah layanan internet yang paling populer saat ini internet mulai dikenal dan digunakan secara luas setelah adanya layanan WWW . WWW adalah halaman-halaman website yang dapat saling terkoneksi satu dengan lainnya (hyperlink) yang membentuk samudra belantara informasi . WWW berjalan dengan protokol HyperText Transfer Protokol (HTTP). Halaman Web merupakan file teks murni (plain text) yang berisi sintaks-sintaks HTML yang dapat dibuka/ dilihat/ diterjemahkan dengan Internet Browser . Sintaks HTML mampu memuat konten text, gambar, audio, video dan animasi. Kini internet identik dengan web, karena kepopuleran web sebagai standar interface pada lanyanan-layanan yang ada di internet, dari awalnya sebagai penyedia informasi, ini digunakan juga untuk komunikasi dari email sampai dengan chatting, sampai dengan melakukan transaksi binsin (commerce) (Betha Sidik,Ir, Pemrograman web dengan HTML, Informatika Bandung, 2005) Banyak keuntungan yang diberikan oleh Aplikasi berbasis Web dari pada aplikasi berbasis destop, sehingga aplikasi berbasis web telah diadopsi oleh perusahaan sebagai bagian dari strategi teknologi informasinya, karena beberapa alasan :<br>Akses informasi mudah,<br>Setup server lebih mudah<br>Informasi mudah didistribusikan<br>Bebas platform, informasi dapat di sajikan oleh browser web pada sistem operasi mana saja karena adanya standar dokumen berbagai tipe data dapat disajikan</div>', NULL, '2022-05-22 16:27:16', '2022-05-22 16:27:16');
INSERT INTO `posts` (`id`, `category_id`, `user_id`, `title`, `slug`, `image`, `excerpt`, `body`, `publish_at`, `created_at`, `updated_at`) VALUES
(35, 3, 1, 'Mobile Programming untuk mahasiswa', 'mobile-programming-untuk-mahasiswa', NULL, 'Pengertian Pemrograman MobilePemrograman Mobile adalah pemrograman yang ditujukan untuk pembuatan aplikasi diperangkat mobile yang dapat kita buat dengan menggunakan Java. Keterbatasan yang sangat umu...', '<div><strong>Pengertian Pemrograman Mobile</strong><br><br>Pemrograman Mobile adalah pemrograman yang ditujukan untuk pembuatan aplikasi diperangkat mobile yang dapat kita buat dengan menggunakan Java. Keterbatasan yang sangat umum dalam bahasa pemrograman untuk peralatan mobile adalah kendala dalan segala dalam hal sumber daya, seperti ukuran layar, memori, CPU, penyimpanan dan cara menginput data. Perbedaan tampilan juga disebabkan adanya<br>perbedaan hardware dan API yang di gunakan. Berikut macam-macam Mobile Programming untuk ponsel :<br>J2ME<br>C++<br>Objective C<br>C#.<br>Javafx<br>PHP<br>Seperti namanya Mobile Programing adalah pemrogaman yang diterapkan di mobile/Handphone atau Laptop. Macam alat mobile yaitu antara lain :<br>Telepon Wireless<br>Tablet PC<br>Smartphone<br>Laptop<br>Handphone<br>dll<br>Pengembangan aplikasi mobile adalah proses dimana aplikasi perangkat lunak yang dikembangkan untuk daya rendah perangkat genggam , seperti asisten pribadi digital , perusahaan asisten digital atau ponsel . Aplikasi ini dapat diinstal pada ponsel selama manufaktur, didownload oleh pelanggan dari berbagai platform distribusi perangkat lunak ponsel , atau disampaikan sebagai aplikasi web menggunakan server-side atau sisi klien pengolahan (misalnya JavaScript) untuk memberikan pengalaman \"aplikasi-seperti\" dalam sebuah browser Web . Pengembang perangkat lunak aplikasi juga harus mempertimbangkan array panjang ukuran layar, spesifikasi hardware dan konfigurasi karena persaingan yang ketat dalam perangkat lunak mobile dan perubahan dalam setiap platform.<br><br>Sejarah &amp; Perkembangan<br>Perkembangan mobile computer hingga kini sangatlah luar biasa. Hal ini tidak lepas dari perkembangan-perkembangan mobile computer dari waktu ke waktu. Berikut dibahas sedikit mengenai sejarah perkembangan mobile computer, yakni :<br><br>Dynabook (1968)<br>Alan kay mengembangkan sebuah komputer portabel yang nantinya menawarkan sebuah media elektronik yang modern yang diperuntukan untuk anak anak. Graphical control interface dengan icon pada Komputer ini merupakan cikal bakal dari system operasi yang ada saat ini.<br><br><br></div>', NULL, '2022-05-22 16:28:11', '2022-05-22 16:28:11'),
(36, 2, 1, 'Kecerdasan Buatan/Artificial Intelligence', 'kecerdasan-buatan-artificial-intelligence', NULL, 'Sejarah Kecerdasan BuatanIstilah kecerdasan buatan diciptakan pada tahun 1956, tetapi AI telah menjadi kian populer saat ini berkat peningkatan volume data, algoritme canggih, dan peningkatan daya ser...', '<div><strong>Sejarah Kecerdasan Buatan</strong><br><br>Istilah kecerdasan buatan diciptakan pada tahun 1956, tetapi AI telah menjadi kian populer saat ini berkat peningkatan volume data, algoritme canggih, dan peningkatan daya serta penyimpanan komputasi.<br><br>Riset AI awal pada tahun 1950-an mengeksplorasi topik-topik seperti penyelesaian masalah dan metode simbolik. Pada tahun 1960-an, Departemen Pertahanan AS menaruh minat terhadap jenis pekerjaan ini dan mulai melatih komputer-komputer untuk menirukan penalaran manusia yang mendasar. Misalnya, Defense Advanced Research Projects Agency (DARPA) menyelesaikan proyek pemetaan jalan pada tahun 1970-an. Dan DARPA menghasilkan asisten pribadi cerdas pada tahun 2003, jauh sebelum Siri, Alexa atau Cortana diberi nama.<br><br>Pekerjaan awal ini membuka jalan bagi otomatisasi dan penalaran formal yang kita lihat di komputer saat ini, termasuk sistem pendukung keputusan dan sistem pencarian pintar yang dapat dirancang untuk melengkapi serta meningkatkan kemampuan manusia.<br><br>Sementara film-film Hollywood dan novel fiksi ilmiah menggambarkan AI sebagai robot mirip manusia yang mengambil alih dunia, evolusi teknologi AI saat ini tidak begitu menakutkan – atau cukup pintar. Sebaliknya, AI telah berevolusi untuk memberikan banyak manfaat spesifik di setiap industri. Teruslah membaca tentang contoh modern kecerdasan buatan dalam perawatan kesehatan, retail, dan lainnya.</div>', NULL, '2022-05-22 16:28:56', '2022-05-22 16:28:56'),
(37, 1, 2, 'Berkenalan Dengan Pemrograman Web', 'berkenalan-dengan-pemrograman-web', NULL, 'Apa Itu Pemrograman Web? Web Programming atau Pemrograman Web merupakan istilah yang erat kaitannya dengan internet dan website. Memang benar, karena pemrograman web merupakan suatu proses pembuatan w...', '<div><strong>Apa Itu Pemrograman Web? </strong><br><br>Web Programming atau Pemrograman Web merupakan istilah yang erat kaitannya dengan internet dan website. Memang benar, karena pemrograman web merupakan suatu proses pembuatan website untuk keperluan internet. Orang banyak mengenal web dengan istilah WWW atau World Wide Web.<br><br>Bahasa Pemrograman Web&nbsp;<br><br>Dalam semua ilmu tentang pemrograman baik itu desktop, mobile, game maupun software atau aplikasi lainnya pasti selalu ada bahasa-bahasa pemrograman yang digunakan untuk membuat aplikasi tersebut yang berisi statement-statement, perintah, atau pun fungsi agar aplikasi yang dibuat sesuai dengan apa yang telah didesain oleh si programmer. Oleh karena itu pemrograman web pun memiliki banyak bahasa yang digunakan, di antaranya:<br><br>HyperText Markup Language (HTML)<br>HTML sebenarnya bukan sebuah bahasa pemrograman, melainkan markup language atau bahasa penandaan yang terdiri dari kumpulan tag. Pada dasarnya HTML hanya mendeskripsikan bahwa bagian tertentu dalam sebuah halaman web adalah isi yang harus ditampilkan oleh browser dengan cara tertentu. HTML merupakan standar internet yang didefinisikan dan dikendalikan oleh World Wide Web Consortium (W3C).<br><br>Cascading Style Sheet (CSS)<br>CSS merupakan bahasa stylesheet yang digunakan untuk mengatur tampilan suatu dokumen yang ditulis dengan HTML. CSS juga memiliki css framework dan digunakan untuk menambah desain-desain tertentu pada halaman web agar desain halaman menarik untuk dilihat. Penggunaan CSS paling umum adalah untuk mengatur halaman web yang ditulis dengan HTML atau XHTML.<br><br>Hypertext Preprocessor (PHP)<br>Bahasa pemrograman PHP merupakan salah satu bahasa scripting yang wajib dikuasai oleh seorang web developer. Karena sifatnya yang server-side scripting, maka untuk menjalankan bahasa pemrograman PHP tidak bisa hanya memanggil file yang berekstensi PHP saja. Bahasa pemrograman PHP memerlukan sebuah web server untuk menjalankannya. PHP juga dapat diintegrasikan dengan HTML, JavaScript, jQuery, Ajax dan lain sebagainya. Akan tetapi pada umumnya bahasa pemrograman PHP digunakan bersamaan dengan file yang bertipe HTML agar file tersebut dapat menjalankan berbagai fungsi.</div>', NULL, '2022-05-22 16:29:44', '2022-05-23 07:35:44'),
(45, 1, 2, 'test', 'test', NULL, 'test', '<div>test</div>', NULL, '2022-07-21 20:18:56', '2022-07-21 20:18:56');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `is_admin` tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `name`, `username`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`, `is_admin`) VALUES
(1, 'Zulfikar Nurdiana', 'zulnurdiana', 'zulnurdiana@gmail.com', NULL, '$2y$10$S4Va1bIQtjj8b8tsuUA2LuhiRVo4WNc7WfFgRHpDH8EY1qq7BHnWO', NULL, '2022-05-22 16:17:04', '2022-05-22 16:17:04', 0),
(2, 'Administrator', 'admin', 'admin@gmail.com', NULL, '$2y$10$2/9dWjuq7ik79hZQRfMjGOkpuDxMhtDW4WpKdWKJ3ZblPL7k.nYN.', NULL, '2022-05-22 16:17:04', '2022-05-22 16:17:04', 0),
(3, 'Umar Mandala', 'nanggraini', 'jumadi06@example.org', '2022-05-22 16:17:05', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'EaOfXuy2CsSiIQWpbgrgEXGpPLhNLArTV7d4ZABFKiUDMOPprB69KG54crWh', '2022-05-22 16:17:05', '2022-05-22 16:17:05', 0),
(4, 'Carub Lanang Halim', 'asmianto.widodo', 'maryati.wisnu@example.org', '2022-05-22 16:17:05', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'rCN8H0j2hPB7qSAqWB54jqyd7G61KQOce6DvgYdSqRpMUNA0XWJSq7emJvhu', '2022-05-22 16:17:05', '2022-05-22 16:17:05', 0),
(5, 'Hairyanto Suryono', 'ian.puspasari', 'safitri.nugraha@example.net', '2022-05-22 16:17:05', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '1Cqsn3RQEk', '2022-05-22 16:17:05', '2022-05-22 16:17:05', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `categories_name_unique` (`name`),
  ADD UNIQUE KEY `categories_slug_unique` (`slug`);

--
-- Indexes for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`);

--
-- Indexes for table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `password_resets`
--
ALTER TABLE `password_resets`
  ADD KEY `password_resets_email_index` (`email`);

--
-- Indexes for table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
  ADD KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`);

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `posts_slug_unique` (`slug`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_username_unique` (`username`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `personal_access_tokens`
--
ALTER TABLE `personal_access_tokens`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=46;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
